// <auto-generated />
namespace DotNetAppSqlDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MudandoIdEscolaPasseio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MudandoIdEscolaPasseio));
        
        string IMigrationMetadata.Id
        {
            get { return "201910052151369_MudandoIdEscolaPasseio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
